version: 2
jobs:
  build:
    docker:      
      - image: ruby:latest
    environment:
      BUNDLE_DIR: vendor/bundle
    
    working_directory: src

    steps:
      - checkout

      - restore_cache:
          name: "[Node.js] Restore Cache"
          keys:
            - nodejs-6.10.2
            - nodejs-

      - run:
          name: "[Node.js] Install"
          command: |
            if [[ ! -e /usr/local/bin/node || $(node --version) != "v${NODEJS_VERSION}" ]]; then
              # https://nodejs.org/ja/download/package-manager/#debian-and-ubuntu-based-linux-distributions-debian-ubuntu-linux
              curl -sL https://deb.nodesource.com/setup_6.x | bash -
              apt-get update -qq
              apt-get install -y nodejs
              ln -s /usr/local/bin/node /usr/local/bin/nodejs
            fi

      - save_cache:
          name: "[Node.js] Save Cache"
          key: nodejs-6.10.2
          paths:
            - /usr/local/bin/node

      - run:
          name: Check Runtime Information
          command: |
            cat << EOF
            bundler        : `bundle -v`
            Node.js        : `node -v`
            EOF

      - restore_cache:
          name: "[Ruby] Restore Cache"
          keys:
            - gems-{{ checksum "Gemfile.lock" }}
            - gems-

      - run: bundle check --path=$BUNDLE_DIR || bundle install --path=$BUNDLE_DIR --jobs=4 --retry=3 --without=production

      - save_cache:
          name: "[Ruby] Save Cache"
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle/

      - restore_cache:
          name: "[JavaScript] Restore Cache"
          keys:
            - js-packages-{{ checksum "package-lock.json" }}
            - js-packages-

      - run: npm install

      - save_cache:
          name: "[JavaScript] Save Cache"
          key: js-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

      - run: npm test
      - run: npm run lint
