version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest-node
    environment:
      BUNDLE_DIR: vendor/bundle
      CACHE_VERSION: 1 # Increment it if you need to purge the cache

    steps:
      - checkout

      - run:
          name: Check Runtime Information
          command: |
            cat << EOF
            ruby           : `ruby -v`
            bundler        : `bundle -v`
            Node.js        : `node -v`
            npm            : `npm -v`
            EOF

      - restore_cache:
          name: "[Ruby] Restore Cache"
          keys:
            - gems-{{ .Environment.CACHE_VERSION }}-{{ checksum "ts_assets.gemspec" }}
            - gems-{{ .Environment.CACHE_VERSION }}-

      - run: bundle check --path=$BUNDLE_DIR || bundle install --path=$BUNDLE_DIR --jobs=4 --retry=3 --without=production

      - save_cache:
          name: "[Ruby] Save Cache"
          key: gems-{{ .Environment.CACHE_VERSION }}-{{ checksum "ts_assets.gemspec" }}
          paths:
            - vendor/bundle/

      - restore_cache:
          name: "[JavaScript] Restore Cache"
          keys:
            - js-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
            - js-packages-{{ .Environment.CACHE_VERSION }}-

      - run: npm install

      - save_cache:
          name: "[JavaScript] Save Cache"
          key: js-packages-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

      - run: bundle exec rake test
      - run: npm run lint
